version: '3.8'

services:
  # 数据库服务 - 使用 OpenGauss（兼容 PostgreSQL）
  database:
    image: enmotech/opengauss:3.1.0
    container_name: zjut_database
    environment:
      - GS_PASSWORD=Enmo@123
      - GS_DB=db_zjut
      - GS_USERNAME=db_user30
    ports:
      - "5432:5432"
    volumes:
      - ./database_data:/var/lib/opengauss/data
      - ./system.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./backend/database/data.sql:/docker-entrypoint-initdb.d/02-data.sql
    networks:
      - zjut_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "gs_ctl status -D /var/lib/opengauss/data"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Redis 缓存服务
  redis:
    image: redis:7-alpine
    container_name: zjut_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - zjut_network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 后端服务 - Spring Boot
  backend:
    build:
      context: ./backend/database
      dockerfile: Dockerfile
    container_name: zjut_backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:opengauss://database:5432/db_zjut
      - SPRING_DATASOURCE_USERNAME=db_user30
      - SPRING_DATASOURCE_PASSWORD=Enmo@123
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SERVER_PORT=9091
    ports:
      - "9091:9091"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - zjut_network
    restart: unless-stopped
    volumes:
      - backend_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  # 前端服务 - Vue.js with Nginx
  frontend:
    build:
      context: ./frontend/database
      dockerfile: Dockerfile
    container_name: zjut_frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - zjut_network
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 数据库管理工具 - pgAdmin (可选)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: zjut_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@zjut.edu.cn
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - zjut_network
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  zjut_network:
    driver: bridge

volumes:
  database_data:
    driver: local
  redis_data:
    driver: local
  backend_logs:
    driver: local
  pgadmin_data:
    driver: local
