spring.application.name: my-application

server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/databaseproject
    username: gaussdb
    password: openGauss@123
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml


